runtime: python39
entrypoint: gunicorn -b :$PORT app:app --timeout 3600

resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'key.json'

basic_scaling:
  max_instances: 5
  idle_timeout: 3600s

handlers:
  - url: /.*
    script: auto
    secure: always
